export const CRIMINAL_CREATION_REQUEST = "CRIMINAL_CREATION_REQUEST";
export const CRIMINAL_CREATION_SUCCESS = "CRIMINAL_CREATION_SUCCESS";
export const CRIMINAL_CREATION_FAIL = "CRIMINAL_CREATION_FAIL";
export const CRIMINAL_DETAILS_REQUEST = "CRIMINAL_DETAILS_REQUEST";
export const CRIMINAL_DETAILS_SUCCESS = "CRIMINAL_DETAILS_SUCCESS";
export const CRIMINAL_DETAILS_FAIL = "CRIMINAL_DETAILS_FAIL";
