export const CRIMINAL_CREATION_REQUEST = "CRIMINAL_CREATION_REQUEST";
export const CRIMINAL_CREATION_SUCCESS = "CRIMINAL_CREATION_SUCCESS";
export const CRIMINAL_CREATION_FAIL = "CRIMINAL_CREATION_FAIL";
