export const GET_CRIMINAL_MAP_lOCATION_REQUEST = 'GET_CRIMINAL_MAP_lOCATION_REQUEST';
export const GET_CRIMINAL_MAP_lOCATION_SUCCESS = 'GET_CRIMINAL_MAP_lOCATION_SUCCESS';
export const GET_CRIMINAL_MAP_lOCATION_FAIL = 'GET_CRIMINAL_MAP_lOCATION__FAIL';