export const CRIME_CREATION_REQUEST = "CRIME_CREATION_REQUEST";
export const CRIME_CREATION_SUCCESS = "CRIME_CREATION_SUCCESS";
export const CRIME_CREATION_FAIL = "CRIME_CREATION_FAIL";

export const GET_CRIME_REQUEST = "GET_CRIME_REQUEST";
export const GET_CRIME_SUCCESS = "GET_CRIME_SUCCESS";
export const GET_CRIME_FAIL = "GET_CRIME_FAIL";