export const HOSPITAL_CREATION_REQUEST = 'HOSPITAL_CREATION_REQUEST';
export const HOSPITAL_CREATION_SUCCESS = 'HOSPITAL_CREATION_SUCCESS';
export const HOSPITAL_CREATION_FAIL = 'HOSPITAL_CREATION_FAIL';
