export const LABORATORY_CREATION_REQUEST = 'LABORATORY_CREATION_REQUEST';
export const LABORATORY_CREATION_SUCCESS = 'LABORATORY_CREATION_SUCCESS';
export const LABORATORY_CREATION_FAIL = 'LABORATORY_CREATION_FAIL';
