export const PATIENT_CREATION_REQUEST = 'PATIENT_CREATION_REQUEST';
export const PATIENT_CREATION_SUCCESS = 'PATIENT_CREATION_SUCCESS';
export const PATIENT_CREATION_FAIL = 'PATIENT_CREATION_FAIL';

export const GET_PATIENT_DISEASES_REQUEST = 'GET_PATIENT_DISEASES_REQUEST';
export const GET_PATIENT_DISEASES_SUCCESS = 'GET_PATIENT_DISEASES_SUCCESS';
export const GET_PATIENT_DISEASES_FAIL = 'GET_PATIENT_DISEASES_FAIL';

export const CREATE_PATIENT_DISEASES_REQUEST = 'CREATE_PATIENT_DISEASES_REQUEST';
export const CREATE_PATIENT_DISEASES_SUCCESS = 'CREATE_PATIENT_DISEASES_SUCCESS';
export const CREATE_PATIENT_DISEASES_FAIL = 'CREATE_PATIENT_DISEASES_FAIL';

export const CREATE_PATIENT_PRESCRIPTION_REQUEST = 'CREATE_PATIENT_PRESCRIPTION_REQUEST';
export const CREATE_PATIENT_PRESCRIPTION_SUCCESS = 'CREATE_PATIENT_PRESCRIPTION_SUCCESS';
export const CREATE_PATIENT_PRESCRIPTION_FAIL = 'CREATE_PATIENT_PRESCRIPTION_FAIL';

