export const PATIENT_CREATION_REQUEST = 'PATIENT_CREATION_REQUEST';
export const PATIENT_CREATION_SUCCESS = 'PATIENT_CREATION_SUCCESS';
export const PATIENT_CREATION_FAIL = 'PATIENT_CREATION_FAIL';

export const GET_PATIENT_DISEASES_REQUEST = 'GET_PATIENT_DISEASES_REQUEST';
export const GET_PATIENT_DISEASES_SUCCESS = 'GET_PATIENT_DISEASES_SUCCESS';
export const GET_PATIENT_DISEASES_FAIL = 'GET_PATIENT_DISEASES_FAIL';
