export const GET_PATIENT_MAP_lOCATION_REQUEST = 'GET_PATIENT_MAP_lOCATION_REQUEST';
export const GET_PATIENT_MAP_lOCATION_SUCCESS = 'GET_PATIENT_MAP_lOCATION_SUCCESS';
export const GET_PATIENT_MAP_lOCATION_FAIL = 'GET_PATIENT_MAP_lOCATION__FAIL';